import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshCombat,initializeObject,damageObject,tickCombat,spawnGroup,lineOfSight,fenceObjects} from '../src/worlds/safehouse/combat';
import {choosePlacement,route} from '../src/worlds/safehouse/placement';
import {sceneryObjects} from '../src/worlds/safehouse/scenery';
import type {SafehouseObject,GroundPoint} from '../src/shared/safehouseTypes';
import {createSafehouseWorld} from '../src/worlds/safehouse';
import type {WorldCtx} from '../src/engine/world';
import type {SafehouseState} from '../src/worlds/safehouse/state';
import {HOUSE_ID} from '../src/shared/safehouseLayout';
function object(id:string,role:SafehouseObject['role'],position:GroundPoint):SafehouseObject{return initializeObject({id,role,position,revision:1,createdAt:0,createdBy:'a',editedBy:'a',footprint:{width:2,depth:1},blueprint:{name:id,description:'test',parts:[{shape:'box',position:[0,.5,0],size:[2,1,1],rotation:[0,0,0],color:'#888888'}]}})}
test('ground placement outside backyard and explicit blocked/outside rejection',()=>{assert.deepEqual(choosePlacement({width:2,depth:1},[],{x:1.55,z:2.5},undefined,{x:3,z:10}).position,{x:3,z:10});assert.throws(()=>choosePlacement({width:2,depth:1},sceneryObjects(),{x:1,z:3},undefined,{x:0,z:-6}),'inside the house');assert.throws(()=>choosePlacement({width:2,depth:1},[],{x:1,z:3},undefined,{x:100,z:10}));});
test('turret range, line of sight and cooldown produce deaths',()=>{const c=freshCombat(false);spawnGroup(c,1);c.zombies[0].position={x:3,z:14};const gun=object('gun','turret',{x:3,z:10});assert.equal(lineOfSight(gun.position,c.zombies[0].position,[gun],gun.id),true);tickCombat(c,[gun],250);assert.equal(c.zombies[0].health,40);tickCombat(c,[gun],250);assert.equal(c.zombies[0].health,40);for(let i=0;i<12;i++)tickCombat(c,[gun],250);assert.equal(c.kills,1);assert.equal(c.zombies.length,0);});
test('barriers stop turret shots and distant zombies do not take damage',()=>{const gun=object('gun','turret',{x:3,z:10}),wall=object('wall','barrier',{x:3,z:12});assert.equal(lineOfSight(gun.position,{x:3,z:15},[gun,wall],gun.id),false);const c=freshCombat(false);spawnGroup(c,1);c.zombies[0].position={x:25,z:18};tickCombat(c,[gun],1000);assert.equal(c.zombies[0].health,60);});
test('zombies approach, attack in reach, and create rubble then archive',()=>{let objects=[object('wall','barrier',{x:3,z:15})];objects[0].health=8;const c=freshCombat(false);spawnGroup(c,1);c.zombies[0].position={x:3,z:16};for(let i=0;i<20;i++)objects=tickCombat(c,objects,500).objects;assert.equal(objects[0].health,0);assert.ok(objects[0].destroyedAt!==undefined);assert.equal(objects[0].revision,1);for(let i=0;i<30;i++)objects=tickCombat(c,objects,500).objects;assert.equal(objects.length,0);assert.equal(c.archive[0].blueprint.name,'wall');});
test('paused and oversized elapsed time cannot erase a world or exceed caps',()=>{const c=freshCombat();const wall=object('wall','barrier',{x:3,z:15});spawnGroup(c,100);assert.equal(c.zombies.length,24);tickCombat(c,[wall],86400000);assert.equal(c.time,0);c.paused=false;tickCombat(c,[wall],86400000);assert.equal(c.time,1000);c.archive=Array.from({length:100},(_,i)=>object('old'+i,'decoration',{x:0,z:0}));tickCombat(c,[wall],500);assert.equal(c.paused,true);});
test('fence collision uses same destructible objects as rendering',()=>{const fences=fenceObjects();const f=fences.find(o=>o.id==='fence-0')!;assert.ok(route({x:6,z:3},{x:6,z:7},fences));assert.equal(f.role,'barrier');damageObject(f,1000,0);assert.equal(f.destroyedAt,0);assert.equal(f.lifecycle,2);});
test('repair, rebuild and visual edits preserve combat invariants',async()=>{const world=createSafehouseWorld({ seedScenery: false,fixture:true,workMs:500});const s=world.createInitialState(0);s.objects=[object('defense1','barrier',{x:3,z:10})];let now=10000;const ctx:WorldCtx<SafehouseState>={state:s,get now(){return now},checkpoint(){world.stateSchema.parse(s)},say(){},log(){},enqueueTask:()=>({id:''}),queue:[],llm:{dialogue:async()=>null,moderate:async()=>({ok:false})},tuning:{},chatRatePerMin:0,rng:()=>.5};world.start?.(ctx);
 async function request(text:string,userId='a'){now+=4000;await world.intents[0].handle(ctx,{id:crypto.randomUUID(),userId,username:userId,text,ts:now,source:'dev'},undefined);for(let i=0;i<200;i++){now+=500;world.tick(ctx,500);await new Promise(r=>setImmediate(r));if(!s.jobs.some(j=>!['complete','failed'].includes(j.status)))break;}}
 damageObject(s.objects[0],100,0);await request('Paint defense1 red');assert.equal(s.objects[0].health,140);world.adminActions!.find(a=>a.id==='safehouse-undo')!.run(ctx);assert.equal(s.objects[0].blueprint.parts[0].color,'#888888');assert.equal(s.objects[0].health,140,'undo restores the look, never the health');
 await request('Repair defense1');assert.equal(s.objects[0].health,240);damageObject(s.objects[0],1000,0);await request('Rebuild defense1');assert.equal(s.objects[0].health,240);assert.equal(s.objects[0].destroyedAt,undefined);assert.equal(s.objects[0].createdBy,'a');assert.equal(s.combat.archive.length,0);
 // A repair heals to the piece's own maximum, not the role default (600-hp walls used to come back at 240).
 const house=sceneryObjects().find(o=>o.id===HOUSE_ID)!;s.objects.push(house);damageObject(house,1500,0);assert.equal(house.health,2500);await request('Repair the house','b');const fixed=s.objects.find(o=>o.id===HOUSE_ID)!;assert.equal(fixed.health,4000);assert.equal(fixed.maxHealth,4000);
});
